### PR TITLE
Migrate to typescript and jest

### LINKED ISSUE #24: Consider adding typescript definitions
Your package looks awesome. Would it be possible to add typescript definitions to your package and/or to definitelytyped? Thanks!

### LINKED ISSUE #36: Migrate from grunt to npm scripts
This would probably involve using `release-it` for releases.

### PR DESCRIPTION
**Pull request by HarelM**
This is basically doing most of the heavy lifting.
There might be some cleaning up to do regarding grunt and jasmine, but I think most of the heavy lifting is done as part of this PR.
Fixes #36 
Fixes #24

- #36 
- #24 

The files are generated in the lib folder to be used when publishing to npm.
e2e seems to work so I didn't see a backwards compatibility issues in terms of public API.
Not sure I'm super excited about the inheritance part, as I prefer composition over inheritance, but I think I managed to change it correctly.

Any feedback is welcome.

To build run `npm run build`
To run tests run `npm run test`

There are also some packages that can probably be removed like lodash, rimraf, make-dir that can be easily done using a one liner I believe.

### CODE REVIEW

**Comment by davidparsson** [comment]
Brilliant, thanks a lot! I'll try to review as soon as possible.

I might split up the initial commit into two, one that modifies everything but the tests and one that modifies the tests, to make sure that the old tests still passes with the new code.

Also, it seems the tests don't pass as is. Are you able to take a look?

**Comment by HarelM** [comment]
Sure, I'll take a look.

**Comment by HarelM** [comment]
A change I did before I pushed that broke the build, sorry, my mistake, should be OK now.

**Comment by HarelM** [comment]
Seems like old node version are failing due to syntax issue. 
I would consider removing those unsupported versions from the CI.
Seems like node 20 is passing the tests.

**Comment by davidparsson** [comment]
Right! I was hoping to make this change non-breaking, but dropping support for node.js versions has been unsupported for years seems reasonable.

However this seems to be caused by `tsc` requiring node.js 14.17+ to compile. I'm not sure it's even worth investigating, but it might still be possible to produce JavaScript that runs on the old versions.

**Comment by HarelM** [comment]
Nodejs 12 is almost 5 years old and is probably considered a security hazard.
I think supporting nodejs from the last 3 years is enough...
Your call. In my OSS projects I support LTS and a version back - i.e. node 20 and node 18 in this case.

**Comment by davidparsson** [comment]
I have merged another PR that dropped support for node.js 14 and older, to `main`. Once this branch has those changes and the tests pass I'll take a closer look at your changes.

Thanks again for your help, and your patience!

**Comment by HarelM** [comment]
I've updated my branch, but you still need to allow the tests to run...

**Comment by HarelM** [comment]
BTW, I've configured my projects to run PRs for people that are not new to github, this solves most of the need to click everytime someone commits a change...

**Comment by davidparsson** [comment]
Thanks! That makes sense. I've done that as well now.

**Comment by davidparsson** [comment]
I've been very busy the last few weeks, but I haven't forgotten about this. I found the need to make a few adjustments, but since I did not have write access to this PR i made a new one in #66.

**Comment by davidparsson** [comment]
Closing this in favor of #66, which contains these changes. I'm still very busy but I'll try to get this reviewed as soon as possible. Thanks!

**Pull request closed without merging**
