### PR TITLE
Add multilineProperty method to test_node

### PR DESCRIPTION
**Pull request by sebastian-sauer**
Some tools allow the property to have a textContent and not use the value attribute. 

See https://github.com/testmoapp/junitxml?tab=readme-ov-file#properties-for-suites-and-cases for examples.

### CODE REVIEW

**Comment by davidparsson** [comment]
Thanks for your contribution! In general I'm happy with it, but I'm not a big fan of boolean flags in public APIs. I can think of two reasonable alternatives:
1. Either we split the property method into two, one that works as befor and one named something like `.textContentProperty(text)`, or
2. we automatically detect line breaks in the provided property value (if it's a string) and use a text content properpty when line breaks are detected.
I'm leaning towards the first option to avoid assumptions and unexpected errors, but having the library do the "right thing" for the user is also appealing. What do you think?

**Comment by sebastian-sauer** [comment]
I like option 1, too. I'll change the PR this evening.

**Comment by sebastian-sauer** [comment]
@davidparsson  i've now added the textContentProperty  - hope the new api is better.

**Comment by davidparsson** [comment]
Thanks, I like this! I'll consider if the names are good enough or if anything should be renamed, but I think I can merge this in its current form.

Thank you for your contribution!

**Comment by sebastian-sauer** [comment]
To be honest - I'm not 100% convinced that the method name is easy to understand :) but as of now I don't have any better name....

**Comment by davidparsson** [comment]
Perhaps `multilineProperty()` is better? That's the use case, right?

**Comment by sebastian-sauer** [comment]
That sounds good. I'll try to update the PR asap.

**Review by davidparsson — APPROVED** [review]
Awesome, thanks! 🤩

**Comment by davidparsson** [comment]
@sebastian-sauer, this is now released in v5.1.0. Thanks!

**Pull request merged**
