### PR TITLE
add property to testcase

### PR DESCRIPTION
**Pull request by Pi-fe**
Hi, I create this fork to add property element to testcase.
I saw there is this https://github.com/davidparsson/junit-report-builder/issues/49 issue open, I hope you want to approve it.

### CODE REVIEW

**Comment by davidparsson** [comment]
Hi! Thanks for your contribution. However, I can't accept it in its current state since tests are failing.

**Comment by Pi-fe** [comment]
Ok, I should fix the error... try now

**Review by davidparsson — CHANGES_REQUESTED** [review]
The changes look reasonable, but new tests are missing. I did not look close enough to spot that when the tests were failing.

I would expect both `spec/test_case_spec.coffee` and `spec/e2e_spec.coffee` to be updated.

Also I'm not over excited over the syntactical (quote) changes that no longer matches the rest of the project.

**Comment by Pi-fe** [comment]
Ok, I restored the syntactical quote changes and I have update tests:
-spec/test_case_spec.coffee
-spec/e2e_spec.coffee

Hope everything is fine this time :)

**Review by davidparsson — APPROVED** [review]
Thanks, this looks fine! I'll try to get a new release out today.

**Comment by Pi-fe** [comment]
Thank you!  I think it could be useful to many :D

**Pull request merged**
