### PR TITLE
1.3.2: Added type/content support for error/failure

### PR DESCRIPTION
**Pull request by rturner-edjuster**
Added support for type attributes on error and failure elements and
added support for content/cdata on the error element.

Incremented version to 1.3.2 and updated release notes.

### CODE REVIEW

**Comment by davidparsson** [comment]
Thanks! I'll get this released right away.

**Comment by rturner-edjuster** [comment]
Thanks. Much appreciated.

**Comment by davidparsson** [comment]
`1.3.2` is published! https://www.npmjs.com/package/junit-report-builder/v/1.3.2

Thank you!

**Comment by rturner-edjuster** [comment]
Thanks for the quick turn-around David.

**Comment by davidparsson** [comment]
A bit late, but this'll be in the readme of the next release at least: https://github.com/davidparsson/junit-report-builder/commit/053fd3703bce9d0601a617411e9a98e304a2ff96

**Pull request merged**
